services: docker
env:
- distro: ubuntu1604
- distro: ubuntu1404
script:
- export container_id=$(date +%s)
- export cleanup=false
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
- chmod +x ${PWD}/tests/test.sh
- "${PWD}/tests/test.sh"
- 'sudo docker exec ${container_id} locale -a | grep -q ''de_DE.utf8''

'
- 'sudo docker exec ${container_id} git --version | grep -q ''git version ''

'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: N4PRyGTivoWnI9jyj1xlc0foDrkqxHAoW8SnOmTNA5kr293hzM+67qmbVxBkzqOs8FEq3hHShB+s+n+6+J3DupeHGymeSHdhLRBqF+vyrgSPY19Nkpecj6qfg80iqRty1ghAs/kgE8yK4yBqGOI9Rkv69hsFT+r/hKoJ93DmZ7M0ZAXGHc8bEKCl7DTNzM1JHfvLJXFKqL4BolKE6vC3gWWpSgUYSmkrHNRM1PFIP0rRjQbPg/STSD8/Gffz1a1ciWWIsV1SlkMa0xS5zrVe0PxAuVJycb38gMiKXU/aW+7RxbPDXaeA7QfrFY0CoNtHoapx/05Y6nCptaRBtMgTD7TOCs4HhnLxT3iKYjgFVbH7fJlS9WwSrUHsYI43ph/WzgKNGE2ybal/95SovsHDp6t10prsaRz4L219fz7X2kPliGa5DSmYAeYDCkYvCxXbXFG6B90cLQytPpiqiBs98Zo8OF7DmHNyn0Af6BV5SduWBvtPDEVbapNevlDxGCwEoDYBW3zQBm+dg/PhuScRcqSFc9n/xA7tVqw4Ej70wOk1rxApXTMexzY2TxrNJziB1xuk00fAt2OEc8SwJPZb53UVifftHGvHi7bt7XNlPfSsCjXilj8TDEW0hgbMateBpT4VkZiapWkVyv8ompJzvJBAxdvCiKVvb5VeTvEbItk=
