---
- name: Get current locales
  become: true
  shell: locale -a
  changed_when: false
  register: installed_locales

- name: Generate locales
  become: true
  shell: "locale-gen {{ item }}"
  when:
    - item not in installed_locales.stdout_lines
  with_items: "{{ required_locales }}"