---

- name: Get current locales
  become: true
  shell: locale -a
  register: installed_locales

- name: Generate locales
  become: true
  shell: locale-gen {{ item }}
  when:
    - "{{ item }} not in {{ installed_locales }}"
  with_items: "{{ required_locales }}"