---
- name: Update APT Cache
  become: true
  changed_when: false
  apt:
    update_cache: yes

- name: Install software
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ additional_software + additional_software_other }}"