---
- name: idempotency check: etc/timezone
  shell: cat etc/timezone
  register: timezone_check
  
- name: delete timezone file if content does not match desired timezone
  file:
    path: /etc/timezone
    state: absent
  when: timezone_check.stdout != {{ timezone }}
  register: timezone_not_set
  
- name: disable current localtime
  become: true
  shell: unlink /etc/localtime
  when: timezone_not_set.changed
  
- name: write timezone file
  lineinfile:
    dest: /etc/timezone
    create: true
    owner: root
    group: root
    mode: 0644
    backup: no
    line: "{{ timezone }}"
  when: timezone_not_set.changed
    
- name: reconfigure timezone
  become: true
  shell: "dpkg-reconfigure --frontend noninteractive tzdata"
  when: timezone_not_set.changed